### PR TITLE
Bump to 4.7.3

### PR DESCRIPTION
**Pull request by jmosbech**

### CODE REVIEW

**Comment by Kikobeats** [comment]
ping @mrmrs 😄

**Comment by johnotander** [comment]
Thanks @jmosbech !

**Comment by johnotander** [comment]
Published to npm as `tachyons-sass@4.7.3`.

**Comment by Kikobeats** [comment]
@johnotander actually we need to generate `4.7.4`

**Comment by johnotander** [comment]
Nice catch @Kikobeats - done : )

**Comment by jmosbech** [comment]
Great! Sorry about the confusion. I looked at the [Github versions](https://github.com/tachyons-css/tachyons/releases) where 4.7.3 is the latest.

**Pull request merged**
